name: CI - Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install client dependencies
      run: |
        cd client
        npm install
        npm audit fix --force
        
    - name: Run client tests
      run: |
        cd client
        npm test --if-present
        
    - name: Build client for production
      run: |
        cd client
        npm run build
        
    - name: Build completed
      run: echo "✅ All builds and tests completed successfully!"