name: Deploy Backend to Railway (Optional)

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main, master ]
    paths: 
      - 'server/**'
      - 'package.json'
      - 'railway.json'

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
        
    - name: Install server dependencies
      run: |
        cd server
        npm ci --omit=dev
        
    - name: Run tests (if available)
      run: |
        cd server
        npm test --if-present
        
    - name: Build success
      run: echo "✅ Backend build completed successfully!"
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && secrets.RAILWAY_TOKEN != ''
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}